### ISSUE TITLE
Typo in OSError exception handling (noetic-devel)

### ISSUE THREAD

**Issue by ScottMcCormack** [jackal/jackal_robot#25]
Noticed a slight typo introduced in commit (https://github.com/jackal/jackal_robot/commit/232ed511d27cb5ef88ea08dbbbf2d45139e4ece3) for the [noetic-devel](https://github.com/jackal/jackal_robot/tree/noetic-devel) branch

https://github.com/jackal/jackal_robot/blob/232ed511d27cb5ef88ea08dbbbf2d45139e4ece3/jackal_bringup/src/jackal_bringup/multicast/daemonize.py#L53

Have opened https://github.com/jackal/jackal_robot/pull/24 to correct this

**Comment by civerachb-cpr** [comment]
Thanks!  The noetic branch is still under development and is definitely not stable (yet!).
