### ISSUE TITLE
Please create a humble-devel branch

### ISSUE THREAD

**Issue by ooeygui** [jackal/jackal_robot#63]
**Describe the the feature you would like**
We're working on supporting Jackal on ROS2 Humble, and have updated the source code to current ROS2 control. We'd like to upstream it to this repo.

Here's our fork of Humble (which currently is brought up on Windows)
https://github.com/ms-iot/jackal_robot/tree/humble

**Comment by tonybaltovski** [comment]
Added the `humble-devel` branch!
