### ISSUE TITLE
Wrong IMU raw values in Foxy

### ISSUE THREAD

**Issue by mllofriu** [jackal/jackal_robot#65]
The ROS1 version of this software had a utility to calibrate the Compass - https://www.clearpathrobotics.com/assets/guides/melodic/jackal/calibration.html.

Is there an existing alternative for Foxy and forward versions?

I was actually looking for something to calibrate the accelerometer, as it seems to be throwing unexpected values with Foxy (e.g. no clear gravity vector). Any guidance on that front will be welcomed too.

**Comment by tonybaltovski** [comment]
Hi @mllofriu, we are looking into this.  It seems like a bug in the firmware that is removing gravity.

**Comment by mllofriu** [comment]
Thanks for the quick response. Do you want me to open a different one regarding compass calibration?

**Comment by tonybaltovski** [comment]
Sure, that would be great! Thanks!

**Comment by mllofriu** [comment]
Just for the sake of our own planning, do you have an estimated time to resolve this? Can we help? I think the firmware is not public, but if you want to share, we can take a look.

**Comment by mllofriu** [comment]
@tonybaltovski, from your github activity I can see you are pretty busy :). But I have to politely insist with my question, as this is blocking a research project in our group. Do you have an ETA for this fix? Or can we help fix it in any way?

**Comment by tonybaltovski** [comment]
Thanks for your patience on this.  Version 1.0.2 of the firmware has the fix for this.  Let me know if you run into any issues.

**Comment by mllofriu** [comment]
This seems to work with 1.02 indeed:

`dpkg -l | grep ros-foxy-jackal-firmware
ii  ros-foxy-jackal-firmware                        1.0.2-focal                          all          Jackal Foxy Firmware
`

`linear_acceleration:
  x: -0.06560111045837402
  y: -0.15806514024734497
  z: 9.800086555480958
`

Thanks!
