### ISSUE TITLE
Having an issue during colcon build when I cloned the jackal_robot package from the foxy-devel branch

### ISSUE THREAD

**Issue by SeifElBouhy** [jackal/jackal_robot#74]
- OS used is Ubuntu 22.04
- Im using ROS2 humble
- Building the jackal_robot package from the **foxy-devel** branch and I received and error on the terminal saying:

"In file included from /home/jackal/jackal_ws/src/jackal_robot/src/jackal_hardware.cpp:35:
/home/jackal/jackal_ws/src/jackal_robot/include/jackal_hardware/jackal_hardware.hpp:43:10: fatal error: hardware_interface/base_interface.hpp: No such file or directory
   43 | #include "hardware_interface/base_interface.hpp"
   
I have installed all the required packages including **ros2control** along with the **hardware_interface** packages. 
Sourcing the /opt/ros/humble/setup.bash before running colcon build, doesn't do anything. Any ideas on how to solve this issue. 
In addition, all packages that I cloned was from the foxy-devel branch.

Reproducing the error:
![Screenshot from 2024-02-01 13-29-27](https://github.com/jackal/jackal_robot/assets/49399570/aedb6c54-e0b0-4a6a-be20-eddb9795bf3a)

**Comment by tonybaltovski** [comment]
@Seif121212 this is for Foxy. For Humble, please use: https://github.com/clearpathrobotics/clearpath_robot
